export const SEARCH_RESULTS_LOADING = 'SEARCH_RESULTS_LOADING'
export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS'
export const SEARCH_RESULTS_FAILED = 'SEARCH_RESULTS_FAILED'

export const MOVIE_FETCH_LOADING = 'MOVIE_FETCH_LOADING'
export const ADD_MOVIE = 'ADD_MOVIE'
export const MOVIE_FETCH_FAILED = 'MOVIE_FETCH_FAILED'